"""Initial migration

Revision ID: 33b713a717d4
Revises: 
Create Date: 2026-05-07 17:31:24.106358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b713a717d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_map',
    sa.Column('code', sa.VARCHAR(length=5), nullable=False),
    sa.Column('long_url', sa.VARCHAR(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_url_map_long_url'), 'url_map', ['long_url'], unique=True)
    op.create_index(op.f('ix_url_map_code'), 'url_map', ['code'], unique=False)
    op.create_table('code_pool',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=5), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False, server_default='available'),
    sa.Column('reserved_at', sa.DATETIME(), nullable=True),
    sa.Column('used_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_pool_status'), 'code_pool', ['status'], unique=False)
    op.create_index(op.f('ix_code_pool_code'), 'code_pool', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_pool_code'), table_name='code_pool')
    op.drop_index(op.f('ix_code_pool_status'), table_name='code_pool')
    op.drop_table('code_pool')
    op.drop_index(op.f('ix_url_map_code'), table_name='url_map')
    op.drop_index(op.f('ix_url_map_long_url'), table_name='url_map')
    op.drop_table('url_map')
    # ### end Alembic commands ###
